#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Validate without modifying or re-staging the user's working tree.
set -euo pipefail
cargo fmt --all -- --check
cargo clippy --locked --workspace --all-targets --all-features -- -D warnings
